version: '3.4'

services:
  myrecipes-recipes-service:
    image: myrecipes-recipes-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8080
      - 80
      - 5005:5005